# ── Application ───────────────────────────────────────────
spring.application.name=api-gateway
server.port=8081

# ── PostgreSQL Database Connection ────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5433/medical_triage
spring.datasource.username=postgres
spring.datasource.password=postgresql987
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ───────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# ── ML Service URL ─────────────────────────────────────────
ml.service.url=http://localhost:8000

# ── Logging ───────────────────────────────────────────────
logging.level.com.medicaltriage=DEBUG
